ImportError: No module named ...
`numba` and `ete3` are said missing when running  `python grapetree.py` in python2.7 virtualenv

`numba` `ete3` and `six` are said missing when running  `python grapetree.py` in a python3.6 virtualenv